### ISSUE TITLE
Compilation broken with cython > 0.25.2

### ISSUE THREAD

**Issue by msklvsk** [fginter/dep_search#13]
Latest cython version breaks the installation.
```
dep_search$ make
make -C setlib
make[1]: Entering directory '/opt/depsearch/dep_search/setlib'
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    language="c++",             # generate C++ code
  File "/opt/depsearch/virtualenv/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 909, in cythonize
    c_options = CompilationOptions(**options)
  File "/opt/depsearch/virtualenv/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 559, in __init__
    raise ValueError(message)
ValueError: got unknown compilation option, please remove: sources
Makefile:7: recipe for target 'pytset.so' failed
make[1]: *** [pytset.so] Error 1
make[1]: Leaving directory '/opt/depsearch/dep_search/setlib'
Makefile:8: recipe for target 'setlib' failed
make: *** [setlib] Error 2
```

However, everything works with `pip install cython==0.25.2`.

**Comment by frankier** [comment]
Patch here: https://github.com/jmnybl/setlib/pull/1
